services:
  - type: web
    name: chernoha-site
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn chernoha.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: "ТВОЙ_СЕКРЕТНЫЙ_КЛЮЧ"
      - key: ALLOWED_HOSTS
        value: "ТВОЙ_ДОМЕН или *"
      - key: EMAIL_HOST_USER
        value: "ТВОЙ_EMAIL"
      - key: EMAIL_HOST_PASSWORD
        value: "ТВОЙ_ПАРОЛЬ_ОТ_EMAIL"
    autoDeploy: true
    plan: free
