# Generated by Django 5.2 on 2025-04-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='category',
            field=models.CharField(choices=[('sweet', 'Сладкие'), ('fresh', 'Свежие'), ('marine', 'Морские')], max_length=10),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
